export const REGLAMENTS_REQUEST = 'REGLAMENTS_REQUEST'
export const CREATE_REGLAMENT_REQUEST = 'CREATE_REGLAMENT_REQUEST'
export const UPDATE_REGLAMENT_REQUEST = 'UPDATE_REGLAMENT_REQUEST'
export const DELETE_REGLAMENT_REQUEST = 'DELETE_REGLAMENT_REQUEST'
