export const REGLAMENT_REQUEST = 'REGLAMENT_REQUEST'
export const REGLAMENTS_REQUEST = 'REGLAMENTS_REQUEST'
export const CREATE_REGLAMENT_REQUEST = 'CREATE_REGLAMENT_REQUEST'
export const UPDATE_REGLAMENT_REQUEST = 'UPDATE_REGLAMENT_REQUEST'
export const DELETE_REGLAMENT_REQUEST = 'DELETE_REGLAMENT_REQUEST'

export const GET_USERS_REGLAMENT_ANSWERS = 'GET_USERS_REGLAMENT_ANSWERS'
export const DELETE_USERS_REGLAMENT_ANSWERS = 'DELETE_USERS_REGLAMENT_ANSWERS'
export const CRATE_USER_REGLAMENT_ANSWER = 'CRATE_USER_REGLAMENT_ANSWER'
